### ISSUE TITLE
import window from 'window'

### ISSUE THREAD

**Issue by oliviertassinari** [zeusdeux/isInViewport#36]
I'm not sure to follow, what's the expected behavior of that line of code?

```jsx
import window from 'window'
```

> ERROR in ./~/is-in-viewport/lib/isInViewport.js
Module not found: Error: Can't resolve 'window' in '*/node_modules/is-in-viewport/lib'

**Comment by zeusdeux** [comment]
What are you using as your bundler?
You should be able to declare window as a global and have the bundler inject the global. Have a look at the es6-example in the examples folder.

**Comment by oliviertassinari** [comment]
I see your point. I'm using webpack here. It's the first time I'm seeing that pattern. Why not using the global window if defined?

**Comment by zeusdeux** [comment]
Well, I leave that upto bundling from your end so that you can actually use the ES6 module version. This let's your bundler create more efficient bundles (for e.g., by enabling rollup to do its tree shaking magic). If you want that logic to already be in there, require lib/isInViewport.js instead of what main and module in the package.json here define.

**Comment by oliviertassinari** [comment]
I'm closing the issue, thanks for making your point.

**Comment by zeusdeux** [comment]
👍🏻👍🏻
