### ISSUE TITLE
 Error: Cannot find module 'window'

### ISSUE THREAD

**Issue by andyinabox** [zeusdeux/isInViewport#43]
I'm using this module in a browserify project and getting the following error when I try and build:

`Error: Cannot find module 'window' from '[path to project]/node_modules/is-in-viewport/lib'`

I'm including the plugin after I include jQuery, and jquery is a available as a module with the correct name:

```js
var jQuery = $ = require('jquery');
require('is-in-viewport');
```

Any thoughts on what might be going on here?

**Comment by zeusdeux** [comment]
I can't find a straightforward way to do this. I have tried `browserify-shim`, adding a `browser` field in the `package.json` field here, `aliasify` but all to no avail. The problem is that browserify supports no way of declaring aliases for imports nor does provide a way, that I can find, of providing a definition for a package or removing a require call and replacing it with a global. On top of this, it doesn't call `window` as `window` but instead as `global` which makes life a bit _more_ harder.

I am quite lost and I apologise for the troubles. If anyone here can come up with a solution, I am all ears.

**Comment by ForkInSpace** [comment]
Hi @zeusdeuxm, i've recently had a similar trouble and that's how I solved it ->
`window.jQuery = require('jquery');
window.$ = global.jQuery;`

Not having seen your code that's the best I can suggest.

**Comment by zeusdeux** [comment]
Hey @ForkInSpace! I think your fix would work for #39 and not this. Nevertheless, is there a project I could look at where you have your fix and build using broswerify please?

**Comment by sapolio** [comment]
I'm experiencing a similar problem in webpack.
> ERROR in ./node_modules/is-in-viewport/lib/isInViewport.es6.js
> Module not found: Error: Can't resolve 'window' in 'C:\...\project\node_modules\is-in-viewport\lib'
>  @ ./node_modules/is-in-viewport/lib/isInViewport.es6.js 2:0-27
> ...
Other jQ plugins work fine with this config:
```
new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery'
      })
```
`imports-loader?jQuery=jquery&window.jQuery=jquery&$=jquery!` does not help either

**Comment by sapolio** [comment]
version 2.4.2 works fine
Now trying 3.0.4
Thank you!
